---

- name: graphite-api-configure | Ensure the Graphite API user is exists
  user: name={{graphite_api_user}}

- name: graphite-api-configure | Ensure the Graphite API home is exists
  file: state=directory owner={{graphite_api_user}} group={{graphite_api_group}} path={{graphite_api_home}}

- name: graphite-api-configure | Setup virtualenv
  shell: virtualenv {{graphite_api_home}}/env --python={{graphite_api_python}} creates={{graphite_api_home}}/env/bin/pip
  sudo: yes
  sudo_user: "{{graphite_api_user}}"

- name: graphite-api-configure | Install Graphit API
  pip: name={{item}} executable={{graphite_api_home}}/env/bin/pip
  sudo: yes
  sudo_user: "{{graphite_api_user}}"
  with_items: [flask, gunicorn, graphite-api]

- name: graphite-api-configure | Install Graphit Whisper
  pip: name=whisper executable={{graphite_api_home}}/env/bin/pip
  sudo: yes
  sudo_user: "{{graphite_api_user}}"
  when: graphite_api_whisper

- name: graphite-api-configure | Setup configuration
  template: owner={{graphite_api_user}} group={{graphite_api_group}} dest={{graphite_api_home}}/config.yml src=config.yml.j2
  notify: [ graphite-api restart ]

- name: graphite-api-configure | Setup upstart
  template: dest=/etc/init/graphite-api.conf src=upstart-api.conf.j2
  when: graphite_api_service == 'upstart'
  notify: [ graphite-api restart ]

- name: graphite-api-configure | Setup init
  template: dest=/etc/init.d/graphite-api src=init-api.j2 mode=0755
  when: graphite_api_service == 'init'
  notify: [ graphite-api restart ]

- name: graphite-api-configure | Touch index file
  file: state=touch path={{graphite_api_search_index}} owner={{graphite_api_user}} group={{graphite_api_group}}
  changed_when: False

- name: graphite-api-configure | Configure nginx
  template: src=nginx.conf.j2 dest={{nginx_dir|default('/etc/nginx')}}/sites-available/graphite-api.conf
  notify: [nginx reload]
  when: nginx_enabled and graphite_api_nginx

- name: graphite-api-configure | Enable Nginx site
  file: src={{nginx_dir|default('/etc/nginx')}}/sites-available/graphite-api.conf dest={{nginx_dir|default('/etc/nginx')}}/sites-enabled/graphite-api.conf state=link
  when: nginx_enabled and graphite_api_nginx

- name: graphite-api-configure | Encrypt http auth passwords
  htpasswd: path={{graphite_api_home}}/.htpasswd name={{item.name}} password={{item.password}}
  with_items: graphite_api_nginx_auth_users
  when: graphite_api_nginx_auth

- name: graphite-api-configure | Ensure graphite-api is started
  service: name=graphite-api state=started enabled=yes
