---

- name: Include OS-specific variables.
  include_vars: "{{item}}"
  with_first_found:
  - "{{ ansible_os_family }}-{{ ansible_lsb.codename }}.yml"
  - "{{ansible_os_family}}-default.yml"
  - "default.yml"

- include: install.deb.yml
  when: ansible_os_family == 'Debian'
  tags: [graphite-api, graphite-api-install]

- include: install.yum.yml
  when: ansible_os_family == 'RedHat'
  tags: [graphite-api, graphite-api-install]

- include: configure.yml
  tags: [graphite-api, graphite-api-configure]

- include: carbon.yml
  tags: [graphite-api, graphite-api-carbon]
  when: graphite_api_carbon
