---

- name: graphite-api-install | Install dependencies
  apt: pkg={{ item }}
  with_items:
  - libcairo2
  - libffi-dev
  - libffi6
  - libyaml-dev

- name: graphite-api-install | Setup passlib
  apt: pkg=python-passlib
  when: graphite_api_nginx_auth
